[project]
name = "font-single-stroker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["numpy>=2.4.2", "pillow>=12.1.1"]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "notebook>=7.5.4",
    "pytest>=9.0.2",
    "ruff>=0.15.5",
]

[tool.ruff]
line-length = 120
[tool.ruff.lint]
select = ["E", "F", "I", "UP", "N", "S", "B", "PL", "RUF"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
